[build]
  publish = "dist/image-editor/browser"
  command = "npm config set legacy-peer-deps true && npm install --force && npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 