[build]
  publish = "dist/image-editor/browser"
  command = "npm install --legacy-peer-deps && npm run build:netlify"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 